# .github/workflows/test-mcp-client.yml
name: Test MCP Client

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastmcp

    - name: Check files exist
      run: |
        echo "Checking required files..."
        ls -la
        test -f filesystem_server.py || (echo "❌ filesystem_server.py not found" && exit 1)
        test -f fastmcp_client.py || (echo "❌ fastmcp_client.py not found" && exit 1)
        test -f integration_test.py || (echo "❌ integration_test.py not found" && exit 1)
        echo "✅ All required files found"

    - name: Validate Python syntax
      run: |
        echo "Checking Python syntax..."
        python3 -m py_compile filesystem_server.py
        python3 -m py_compile fastmcp_client.py
        python3 -m py_compile integration_test.py
        echo "✅ Python syntax is valid"

    - name: Run integration tests
      run: |
        echo "Running comprehensive integration tests..."
        python3 integration_test.py

  test-multiple-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastmcp

    - name: Test with Python ${{ matrix.python-version }}
      run: |
        echo "Testing with Python ${{ matrix.python-version }}"
        python3 integration_test.py

  test-import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastmcp

    - name: Test imports
      run: |
        echo "Testing if modules can be imported..."
        python3 -c "import fastmcp_client; print('✅ fastmcp_client imports successfully')"
        python3 -c "from fastmcp_client import FastMCPClient; print('✅ FastMCPClient class imports successfully')"
        python3 -c "import sys; sys.path.append('.'); from filesystem_server import mcp; print('✅ filesystem_server imports successfully')"